export { default as Home } from "./Home";
export { default as Login } from "./Login";
export { default as FolderPage } from "./FolderPage";
export { default as Account } from "./Account";
export { default as Signup } from "./Signup";
export { default as LandingPage } from "./Landing";
export { default as FilePage } from "./FilePage";
export { default as NewFile } from "./NewFile";
export { default as NewFolder } from "./NewFolder";